### ISSUE TITLE
GCC ASAN build unstable

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-security/aws-oncall#14]
GCC ASan build is unstable because of test failures.

Failed tests:
projectroot.test_logging_output_format
rcutils.TestLoggingOutputFormatAfterShutdown.test_processes_exit_codes

Test results [here](https://ci.ros2.org/view/nightly/job/nightly_linux_address_sanitizer/249/testReport/).

**Comment by prajakta-gokhale** [comment]
Tests pass locally but fail on CI because the launch process that starts the tests exits before tests execute

```bash
Task exception was never retrieved
future: <Task finished coro=<LaunchService._process_one_event() done, defined at /home/jenkins-agent/workspace/nightly_linux_address_sanitizer/ws/install/launch/lib/python3.6/site-packages/launch/launch_service.py:289> exception=RuntimeError('Signal event received before subprocess transport available.',)>
Traceback (most recent call last):
  File "/home/jenkins-agent/workspace/nightly_linux_address_sanitizer/ws/install/launch/lib/python3.6/site-packages/launch/launch_service.py", line 291, in _process_one_event
    await self.__process_event(next_event)
  File "/home/jenkins-agent/workspace/nightly_linux_address_sanitizer/ws/install/launch/lib/python3.6/site-packages/launch/launch_service.py", line 311, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/home/jenkins-agent/workspace/nightly_linux_address_sanitizer/ws/install/launch/lib/python3.6/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/home/jenkins-agent/workspace/nightly_linux_address_sanitizer/ws/install/launch/lib/python3.6/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/home/jenkins-agent/workspace/nightly_linux_address_sanitizer/ws/install/launch/lib/python3.6/site-packages/launch/actions/opaque_function.py", line 75, in execute
    return self.__function(context, *self.__args, **self.__kwargs)
  File "/home/jenkins-agent/workspace/nightly_linux_address_sanitizer/ws/install/launch/lib/python3.6/site-packages/launch/actions/execute_process.py", line 383, in __on_signal_process_event
    raise RuntimeError('Signal event received before subprocess transport available.')
RuntimeError: Signal event received before subprocess transport available.
```

**Comment by prajakta-gokhale** [comment]
Clang Thread Safety Annotations build fails similarly (see https://github.com/ros-security/aws-oncall/issues/15).

Fix for this is in https://github.com/ros2/rcutils/pull/193 and it is merged.

**Comment by zmichaels11** [comment]
GCC ASAN is currently passing.
