### ISSUE TITLE
GCC ASAN for rcutils is Unstable

### ISSUE THREAD

**Issue by piraka9011** [ros-security/aws-oncall#30]
The following test is failing on the nightly GCC ASAN build:

[`TestLoggingOutputFormatAfterShutdown.test_processes_exit_codes`](https://ci.ros2.org/view/nightly/job/nightly_linux_address_sanitizer/lastBuild/testReport/junit/rcutils/TestLoggingOutputFormatAfterShutdown/test_processes_exit_codes/)

**Error Message**

```
Traceback (most recent call last):
  File "/home/jenkins-agent/workspace/nightly_linux_address_sanitizer/ws/src/ros2/rcutils/test/test_logging_output_format.py", line 98, in test_processes_exit_codes
    launch_testing.asserts.assertExitCodes(proc_info)
  File "/home/jenkins-agent/workspace/nightly_linux_address_sanitizer/ws/install/launch_testing/lib/python3.6/site-packages/launch_testing/asserts/assert_exit_codes.py", line 64, in assertExitCodes
    info.returncode
AssertionError: Proc test_logging_output_format_long-1 exited with code -2
```

**Comment by piraka9011** [comment]
It appears that this is a flakey test caused by `launch_testing` exiting before the test actually completes.
Need to bump to the `build_cop` to determine if this is being tracked by OSRF as well.

**Comment by prajakta-gokhale** [comment]
The build has moved back to green. Looking at the flakiness [trend](https://ci.ros2.org/view/nightly/job/nightly_linux_address_sanitizer/buildTimeTrend), the next time this test is unstable we should create a ticket in the `launch_testing` to fix the problem.
