### ISSUE TITLE
colcon-bundle Travis build is failing

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-security/aws-oncall#51]
From build logs in latest [Travis build](https://travis-ci.org/colcon/colcon-bundle/builds/636483773):

```bash
Step 22/23 : RUN source /opt/ros/kinetic/setup.sh; colcon bundle --bundle-version 1 --bundle-base v1 --pip-requirements py27_requirements.txt --pip3-requirements py3_requirements.txt
 ---> Running in 607bf6229d31

 ...

ERROR: Package 'setuptools' requires a different Python: 2.7.12 not in '>=3.5'
[63.812s] ERROR:colcon:colcon bundle: Command '['/opt/package/integration/test_workspace/v1/cache/bundle_staging/usr/bin/python2', '-m', 'pip', 'install', '-U', 'pip', 'setuptools']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/colcon_core/command.py", line 483, in verb_main
    rc = context.args.main(context=context)
  File "/opt/package/colcon_bundle/verb/bundle.py", line 138, in main
    upgrade_deps_graph)
  File "/opt/package/colcon_bundle/verb/bundle.py", line 187, in _manage_dependencies
    include_sources=context.args.include_sources)
  File "/opt/package/colcon_bundle/verb/_installer_manager.py", line 78, in run_installers
    installer_metadata[name] = installer.install()
  File "/opt/package/colcon_bundle/installer/base_pip_installer.py", line 86, in install
    subprocess.check_call(pip_install_args + ['-U', 'pip', 'setuptools'])
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/package/integration/test_workspace/v1/cache/bundle_staging/usr/bin/python2', '-m', 'pip', 'install', '-U', 'pip', 'setuptools']' returned non-zero exit status 1
```

The test started failing 2 days ago with the same error for kinetic and melodic ROS distros.

**Comment by piraka9011** [comment]
The tests seemed to fail and then pass again on one of the more recent builds.
On an ubuntu16.04 x86 EC2 with ROS1 Kinetic running the test:

```bash
TEST=backwards ROS_DISTRO=kinetic TOXENV=py35-pypi 
```

I get 

```bash
...
Step 9/23 : RUN pip3 install -r requirements.txt
 ---> Running in 76a909bebe1b
ERROR: Could not find a version that satisfies the requirement actionlib==1.11.13 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for actionlib==1.11.13 (from -r requirements.txt (line 1))
The command '/bin/bash -c pip3 install -r requirements.txt' returned a non-zero code: 1
ERROR: InvocationError for command /home/ubuntu/colcon-bundle/run_integration_test.sh (exited with code 1)
```

instead of 

```bash
The command '/bin/bash -c source /opt/ros/kinetic/setup.sh; colcon bundle --bundle-version 1 --bundle-base v1' returned a non-zero code: 1

ERROR: InvocationError for command /home/travis/build/colcon/colcon-bundle/run_integration_test.sh (exited with code 1)
```
in the test

**Comment by piraka9011** [comment]
It appears that this is a related [issue](https://github.com/pypa/virtualenv/issues/1493)

**Comment by piraka9011** [comment]
Fix submitted here: https://github.com/colcon/colcon-bundle/pull/127
